import jsPDF from 'jspdf'
import 'jspdf-autotable'
import type { VideoAnalysis, AnalysisScores } from '../types'

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: Record<string, unknown>) => jsPDF
  }
}

const SCORE_LABELS: Record<keyof AnalysisScores, string> = {
  communication: 'Communication',
  eyeContact: 'Eye Contact',
  socialEngagement: 'Social Engagement',
  gestures: 'Gestures',
  speechClarity: 'Speech Clarity',
  emotionalResponse: 'Emotional Response',
}

function scoreLevel(score: number): string {
  if (score >= 7) return 'Typical'
  if (score >= 4) return 'Mild Concern'
  return 'Significant Concern'
}

export function generateAnalysisReport(
  analyses: VideoAnalysis[],
  childName: string,
  screeningResult?: { score: number; riskLevel: string; completedAt: string } | null,
) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Kidooo Developmental Report', pageWidth / 2, y, { align: 'center' })
  y += 10

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth / 2, y, { align: 'center' })
  y += 8
  doc.text(`Child: ${childName}`, pageWidth / 2, y, { align: 'center' })
  y += 12
  doc.setTextColor(0)

  // Screening results
  if (screeningResult) {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('M-CHAT-R Screening Results', 14, y)
    y += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Score: ${screeningResult.score}/20`, 14, y)
    y += 5
    doc.text(`Risk Level: ${screeningResult.riskLevel.charAt(0).toUpperCase() + screeningResult.riskLevel.slice(1)}`, 14, y)
    y += 5
    doc.text(`Completed: ${new Date(screeningResult.completedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 14, y)
    y += 12
  }

  // Separator
  doc.setDrawColor(230)
  doc.line(14, y, pageWidth - 14, y)
  y += 8

  // Analyses
  const completed = analyses.filter((a) => a.status === 'completed')
  if (completed.length === 0) {
    doc.setFontSize(10)
    doc.text('No completed analyses to report.', 14, y)
  } else {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(`Video Analyses (${completed.length})`, 14, y)
    y += 10

    for (const analysis of completed) {
      if (y > 260) {
        doc.addPage()
        y = 20
      }

      // Analysis header
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text(`#${analysis.id} — ${analysis.scenarioTitle || analysis.fileName}`, 14, y)
      y += 5

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100)
      const date = new Date(analysis.uploadedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
      doc.text(`${date} | ${analysis.fileName}`, 14, y)
      y += 6
      doc.setTextColor(0)

      // Scores table
      if (analysis.scores) {
        const scoreKeys = Object.keys(SCORE_LABELS) as (keyof AnalysisScores)[]
        const tableData = scoreKeys
          .filter((k) => analysis.scores![k] > 0)
          .map((k) => [SCORE_LABELS[k], `${analysis.scores![k]}/10`, scoreLevel(analysis.scores![k])])

        if (tableData.length > 0) {
          doc.autoTable({
            startY: y,
            head: [['Dimension', 'Score', 'Level']],
            body: tableData,
            margin: { left: 14 },
            styles: { fontSize: 8, cellPadding: 2 },
            headStyles: { fillColor: [245, 158, 11] },
            theme: 'striped',
          })
          y = (doc as unknown as Record<string, number>).lastAutoTable?.finalY + 6 || y + 30
        }
      }

      // Summary
      if (analysis.summary) {
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        const summaryLines = doc.splitTextToSize(analysis.summary, pageWidth - 28)
        if (y + summaryLines.length * 4 > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(summaryLines, 14, y)
        y += summaryLines.length * 4 + 8
      }

      // Separator
      if (y < 260) {
        doc.setDrawColor(240)
        doc.line(14, y, pageWidth - 14, y)
        y += 8
      }
    }
  }

  // Disclaimer
  if (y > 250) {
    doc.addPage()
    y = 20
  }
  doc.setFontSize(7)
  doc.setTextColor(150)
  doc.text(
    'Disclaimer: This report is generated by Kidooo, a screening tool. It is not a diagnostic instrument. Always consult a qualified healthcare professional.',
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' },
  )

  doc.save(`kidooo-report-${childName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`)
}
